### ISSUE TITLE
Exception on schema creation

### ISSUE THREAD

**Issue by ilyaukin** [prakass1/SimplisticBlogger#3]
Seems that it doesn't affect anything, but got an exception in logs during first run.

```
blog_app          | Traceback (most recent call last):
blog_app          |   File "/usr/local/bin/flask", line 8, in <module>
blog_app          |     sys.exit(main())
blog_app          |   File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 967, in main
blog_app          |     cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
blog_app          |   File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 586, in main
blog_app          |     return super(FlaskGroup, self).main(*args, **kwargs)
blog_app          |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
blog_app          |     rv = self.invoke(ctx)
blog_app          |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
blog_app          |     return _process_result(sub_ctx.command.invoke(sub_ctx))
blog_app          |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
blog_app          |     return ctx.invoke(self.callback, **ctx.params)
blog_app          |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
blog_app          |     return callback(*args, **kwargs)
blog_app          |   File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 73, in new_func
blog_app          |     return ctx.invoke(f, obj, *args, **kwargs)
blog_app          |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
blog_app          |     return callback(*args, **kwargs)
blog_app          |   File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 848, in run_command
blog_app          |     app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
blog_app          |   File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 305, in __init__
blog_app          |     self._load_unlocked()
blog_app          |   File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 330, in _load_unlocked
blog_app          |     self._app = rv = self.loader()
blog_app          |   File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 392, in load_app
blog_app          |     app = locate_app(self, import_name, None, raise_if_not_found=False)
blog_app          |   File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 240, in locate_app
blog_app          |     __import__(module_name)
blog_app          |   File "/app/blog/app.py", line 5, in <module>
blog_app          |     app = create_app(config_name)
blog_app          |   File "/app/blog/__init__.py", line 58, in create_app
blog_app          |     db.create_all()
blog_app          |   File "/usr/local/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 1039, in create_all
blog_app          |     self._execute_for_all_tables(app, bind, 'create_all')
blog_app          |   File "/usr/local/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 1031, in _execute_for_all_tables
blog_app          |     op(bind=self.get_engine(app, bind), **extra)
blog_app          |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 4554, in create_all
blog_app          |     ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
blog_app          |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2095, in _run_visitor
blog_app          |     conn._run_visitor(visitorcallable, element, **kwargs)
blog_app          |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1656, in _run_visitor
blog_app          |     visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
blog_app          |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 145, in traverse_single
blog_app          |     return meth(obj, **kw)
blog_app          |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 760, in visit_metadata
blog_app          |     [t for t in tables if self._can_create_table(t)]
blog_app          |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 1195, in sort_tables_and_constraints
blog_app          |     dependent_on = fkc.referred_table
blog_app          |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 3424, in referred_table
blog_app          |     return self.elements[0].column.table
blog_app          |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 884, in __get__
blog_app          |     obj.__dict__[self.__name__] = result = self.fget(obj)
blog_app          |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 2148, in column
blog_app          |     tablekey,
blog_app          | sqlalchemy.exc.NoReferencedTableError: Foreign key associated with column 'posts.user_id' could not find table 'users' with which to generate a foreign key to target column 'id'
```

**Comment by prakass1** [comment]
This error will occur when the blog-admin app is not provisioned. The blog-app depends on the blog-admin-app for creating a root user that the blog creation user whose data will be then taken into blog-app.

This error will go if you do the following:
1. Start the mysql docker container with `docker-compose -f docker-compose-mysql.yml up -d`
2. Build the blog-admin-app with all the env variable of absolute importance are the ports and the admin username/password Example:  
```
ADMIN_USERNAME=admin  
PASSWORD=1234
```
Docker command: `docker-compose build blog-admin-app`
3. The blog-admin-app allows to create the post, moderate comments etc...
4. Once, the blog-admin-app is built, run the docker container as `docker-compose up -d blog-admin-app`
5. Build and run the blog-app as:  
`docker-compose build blog-app`  
`docker-compose up -d blog-app`

I have also added an `.env_example` now to make things easier with setup :)
